# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 16b169f9f67d8a19e76794accb2d515c270bcb88648f3c61d73a3f2d65fb2aaec6af3d27a465eeddac8c39a99a20177ff3d7deb410f08f52821437eda6af212a

test:
  secret_key_base: 733fb213d7601f376e292cf14f63a3199ce69b7ce04f137bc420145ad5f204dad0cb19e5bb74d8d43e6eb944c2521636a81d1d1b5ff830e62563743c7aa5c206

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
